# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choose.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_chooseForm(object):
    def setupUi(self, chooseForm):
        chooseForm.setObjectName("chooseForm")
        chooseForm.resize(484, 298)
        chooseForm.setAcceptDrops(False)
        self.backButton = QtWidgets.QPushButton(chooseForm)
        self.backButton.setGeometry(QtCore.QRect(20, 10, 90, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.backButton.setFont(font)
        self.backButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backButton.setStyleSheet("border-image: url(:/button/button.png);")
        self.backButton.setObjectName("backButton")
        self.startButton = QtWidgets.QPushButton(chooseForm)
        self.startButton.setGeometry(QtCore.QRect(349, 230, 131, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.startButton.setFont(font)
        self.startButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startButton.setStyleSheet("border-image: url(:/button/button.png);")
        self.startButton.setObjectName("startButton")
        self.tipLabel = QtWidgets.QLabel(chooseForm)
        self.tipLabel.setGeometry(QtCore.QRect(120, 50, 160, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tipLabel.setFont(font)
        self.tipLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tipLabel.setObjectName("tipLabel")
        self.primaryButton = QtWidgets.QRadioButton(chooseForm)
        self.primaryButton.setGeometry(QtCore.QRect(120, 170, 70, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.primaryButton.setFont(font)
        self.primaryButton.setObjectName("primaryButton")
        self.middleButton = QtWidgets.QRadioButton(chooseForm)
        self.middleButton.setGeometry(QtCore.QRect(220, 170, 70, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.middleButton.setFont(font)
        self.middleButton.setObjectName("middleButton")
        self.highButton = QtWidgets.QRadioButton(chooseForm)
        self.highButton.setGeometry(QtCore.QRect(310, 170, 70, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.highButton.setFont(font)
        self.highButton.setObjectName("highButton")
        self.changeSecretButton = QtWidgets.QPushButton(chooseForm)
        self.changeSecretButton.setGeometry(QtCore.QRect(370, 10, 90, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.changeSecretButton.setFont(font)
        self.changeSecretButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.changeSecretButton.setStyleSheet("border-image: url(:/button/button.png);")
        self.changeSecretButton.setObjectName("changeSecretButton")
        self.quesNumberBox = QtWidgets.QSpinBox(chooseForm)
        self.quesNumberBox.setGeometry(QtCore.QRect(230, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.quesNumberBox.setFont(font)
        self.quesNumberBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.quesNumberBox.setObjectName("quesNumberBox")
        self.tipLabel_2 = QtWidgets.QLabel(chooseForm)
        self.tipLabel_2.setGeometry(QtCore.QRect(120, 130, 160, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tipLabel_2.setFont(font)
        self.tipLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tipLabel_2.setObjectName("tipLabel_2")
        self.label = QtWidgets.QLabel(chooseForm)
        self.label.setGeometry(QtCore.QRect(-10, -70, 501, 431))
        self.label.setMinimumSize(QtCore.QSize(501, 431))
        self.label.setMaximumSize(QtCore.QSize(501, 431))
        self.label.setStyleSheet("image: url(:/login/login_400_250.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.backButton.raise_()
        self.startButton.raise_()
        self.tipLabel.raise_()
        self.primaryButton.raise_()
        self.middleButton.raise_()
        self.highButton.raise_()
        self.changeSecretButton.raise_()
        self.quesNumberBox.raise_()
        self.tipLabel_2.raise_()

        self.retranslateUi(chooseForm)
        self.backButton.clicked.connect(chooseForm.backToLogin)
        self.startButton.clicked.connect(chooseForm.startDoing)
        self.changeSecretButton.clicked.connect(chooseForm.changeSecret)
        QtCore.QMetaObject.connectSlotsByName(chooseForm)

    def retranslateUi(self, chooseForm):
        _translate = QtCore.QCoreApplication.translate
        chooseForm.setWindowTitle(_translate("chooseForm", "题题会"))
        self.backButton.setText(_translate("chooseForm", "退出登录"))
        self.startButton.setText(_translate("chooseForm", "开始做题→"))
        self.tipLabel.setText(_translate("chooseForm", "请输入题目数量："))
        self.primaryButton.setText(_translate("chooseForm", "小学"))
        self.middleButton.setText(_translate("chooseForm", "初中"))
        self.highButton.setText(_translate("chooseForm", "高中"))
        self.changeSecretButton.setText(_translate("chooseForm", "修改密码"))
        self.tipLabel_2.setText(_translate("chooseForm", "请选择题目难度："))
import back_rc
