# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginForm(object):
    def setupUi(self, loginForm):
        loginForm.setObjectName("loginForm")
        loginForm.resize(400, 250)
        loginForm.setMinimumSize(QtCore.QSize(400, 250))
        loginForm.setMaximumSize(QtCore.QSize(400, 250))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        loginForm.setFont(font)
        loginForm.setAcceptDrops(False)
        self.title = QtWidgets.QLabel(loginForm)
        self.title.setGeometry(QtCore.QRect(100, 10, 200, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.goregisterButton = QtWidgets.QPushButton(loginForm)
        self.goregisterButton.setGeometry(QtCore.QRect(130, 190, 71, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.goregisterButton.setFont(font)
        self.goregisterButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.goregisterButton.setStyleSheet("border-image: url(:/button/button.png);")
        self.goregisterButton.setObjectName("goregisterButton")
        self.gologinButton = QtWidgets.QPushButton(loginForm)
        self.gologinButton.setGeometry(QtCore.QRect(200, 190, 71, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.gologinButton.setFont(font)
        self.gologinButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gologinButton.setStyleSheet("border-image: url(:/button/button.png);")
        self.gologinButton.setObjectName("gologinButton")
        self.passwordEdit = QtWidgets.QLineEdit(loginForm)
        self.passwordEdit.setGeometry(QtCore.QRect(140, 143, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setKerning(False)
        self.passwordEdit.setFont(font)
        self.passwordEdit.setStyleSheet("")
        self.passwordEdit.setMaxLength(10)
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setDragEnabled(False)
        self.passwordEdit.setReadOnly(False)
        self.passwordEdit.setClearButtonEnabled(True)
        self.passwordEdit.setObjectName("passwordEdit")
        self.username = QtWidgets.QLabel(loginForm)
        self.username.setEnabled(True)
        self.username.setGeometry(QtCore.QRect(60, 87, 70, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.username.setFont(font)
        self.username.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.username.setObjectName("username")
        self.usernameEdit = QtWidgets.QLineEdit(loginForm)
        self.usernameEdit.setGeometry(QtCore.QRect(140, 87, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.usernameEdit.setFont(font)
        self.usernameEdit.setAutoFillBackground(False)
        self.usernameEdit.setStyleSheet("")
        self.usernameEdit.setText("")
        self.usernameEdit.setClearButtonEnabled(True)
        self.usernameEdit.setObjectName("usernameEdit")
        self.password = QtWidgets.QLabel(loginForm)
        self.password.setGeometry(QtCore.QRect(60, 143, 70, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.password.setFont(font)
        self.password.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.password.setObjectName("password")
        self.label = QtWidgets.QLabel(loginForm)
        self.label.setGeometry(QtCore.QRect(0, 0, 400, 250))
        self.label.setMinimumSize(QtCore.QSize(400, 250))
        self.label.setMaximumSize(QtCore.QSize(400, 250))
        self.label.setStyleSheet("image: url(:/login/login_400_250.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.title.raise_()
        self.goregisterButton.raise_()
        self.gologinButton.raise_()
        self.passwordEdit.raise_()
        self.username.raise_()
        self.usernameEdit.raise_()
        self.password.raise_()

        self.retranslateUi(loginForm)
        self.gologinButton.clicked.connect(loginForm.loginNow)
        self.goregisterButton.clicked.connect(loginForm.goRegister)
        QtCore.QMetaObject.connectSlotsByName(loginForm)

    def retranslateUi(self, loginForm):
        _translate = QtCore.QCoreApplication.translate
        loginForm.setWindowTitle(_translate("loginForm", "题题会"))
        self.title.setText(_translate("loginForm", "<html><head/><body><p><span style=\" color:#000000;\">题  题  会</span></p></body></html>"))
        self.goregisterButton.setText(_translate("loginForm", "注册"))
        self.gologinButton.setText(_translate("loginForm", "登录"))
        self.username.setText(_translate("loginForm", "<html><head/><body><p><span style=\" color:#000000;\">用户名</span></p></body></html>"))
        self.password.setText(_translate("loginForm", "<html><head/><body><p><span style=\" color:#000000;\">密码</span></p></body></html>"))
import back_rc
