# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_registerForm(object):
    def setupUi(self, registerForm):
        registerForm.setObjectName("registerForm")
        registerForm.resize(657, 418)
        registerForm.setMinimumSize(QtCore.QSize(657, 418))
        registerForm.setMaximumSize(QtCore.QSize(657, 418))
        font = QtGui.QFont()
        font.setKerning(False)
        registerForm.setFont(font)
        registerForm.setAcceptDrops(True)
        registerForm.setAutoFillBackground(False)
        self.backButton = QtWidgets.QPushButton(registerForm)
        self.backButton.setGeometry(QtCore.QRect(20, 30, 90, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setKerning(False)
        self.backButton.setFont(font)
        self.backButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backButton.setStyleSheet("border-image: url(:/button/button.png);")
        self.backButton.setObjectName("backButton")
        self.registerButton = QtWidgets.QPushButton(registerForm)
        self.registerButton.setGeometry(QtCore.QRect(280, 340, 90, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setKerning(False)
        self.registerButton.setFont(font)
        self.registerButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.registerButton.setStyleSheet("border-image: url(:/button/button.png);")
        self.registerButton.setObjectName("registerButton")
        self.phoneNumberLabel = QtWidgets.QLabel(registerForm)
        self.phoneNumberLabel.setGeometry(QtCore.QRect(100, 30, 110, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.phoneNumberLabel.setFont(font)
        self.phoneNumberLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.phoneNumberLabel.setObjectName("phoneNumberLabel")
        self.numberEdit = QtWidgets.QLineEdit(registerForm)
        self.numberEdit.setGeometry(QtCore.QRect(220, 30, 200, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberEdit.sizePolicy().hasHeightForWidth())
        self.numberEdit.setSizePolicy(sizePolicy)
        self.numberEdit.setMinimumSize(QtCore.QSize(200, 30))
        self.numberEdit.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setKerning(False)
        self.numberEdit.setFont(font)
        self.numberEdit.setText("")
        self.numberEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.numberEdit.setPlaceholderText("")
        self.numberEdit.setClearButtonEnabled(True)
        self.numberEdit.setObjectName("numberEdit")
        self.password_9 = QtWidgets.QLabel(registerForm)
        self.password_9.setGeometry(QtCore.QRect(430, 30, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setItalic(False)
        font.setKerning(False)
        self.password_9.setFont(font)
        self.password_9.setObjectName("password_9")
        self.codeLabel = QtWidgets.QLabel(registerForm)
        self.codeLabel.setGeometry(QtCore.QRect(100, 90, 110, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        # self.codeLabel.setFont(font)
        # self.codeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        # self.codeLabel.setObjectName("codeLabel")
        # self.codeEdit = QtWidgets.QLineEdit(registerForm)
        # self.codeEdit.setGeometry(QtCore.QRect(220, 90, 200, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.codeEdit.sizePolicy().hasHeightForWidth())
        # self.codeEdit.setSizePolicy(sizePolicy)
        # self.codeEdit.setMinimumSize(QtCore.QSize(200, 30))
        # self.codeEdit.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setKerning(False)
        # self.codeEdit.setFont(font)
        # self.codeEdit.setMaxLength(4)
        # self.codeEdit.setClearButtonEnabled(False)
        # self.codeEdit.setObjectName("codeEdit")
        # self.sendCodeButton = QtWidgets.QPushButton(registerForm)
        # self.sendCodeButton.setEnabled(True)
        # self.sendCodeButton.setGeometry(QtCore.QRect(430, 90, 180, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.sendCodeButton.sizePolicy().hasHeightForWidth())
        # self.sendCodeButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        # self.sendCodeButton.setFont(font)
        # self.sendCodeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        # self.sendCodeButton.setStyleSheet("")
        # self.sendCodeButton.setAutoDefault(False)
        # self.sendCodeButton.setObjectName("sendCodeButton")
        self.usernameLabel = QtWidgets.QLabel(registerForm)
        self.usernameLabel.setGeometry(QtCore.QRect(100, 150, 110, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.usernameLabel.setObjectName("usernameLabel")
        self.passwordLabel = QtWidgets.QLabel(registerForm)
        self.passwordLabel.setGeometry(QtCore.QRect(100, 210, 110, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.passwordLabel.setObjectName("passwordLabel")
        self.confirmLabel = QtWidgets.QLabel(registerForm)
        self.confirmLabel.setGeometry(QtCore.QRect(100, 270, 110, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.confirmLabel.setFont(font)
        self.confirmLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.confirmLabel.setObjectName("confirmLabel")
        self.tel_2 = QtWidgets.QLabel(registerForm)
        self.tel_2.setGeometry(QtCore.QRect(430, 150, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setItalic(False)
        font.setKerning(False)
        self.tel_2.setFont(font)
        self.tel_2.setObjectName("tel_2")
        self.password_3 = QtWidgets.QLabel(registerForm)
        self.password_3.setGeometry(QtCore.QRect(430, 210, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setItalic(False)
        font.setKerning(False)
        self.password_3.setFont(font)
        self.password_3.setObjectName("password_3")
        self.password_4 = QtWidgets.QLabel(registerForm)
        self.password_4.setGeometry(QtCore.QRect(430, 270, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setItalic(False)
        font.setKerning(False)
        self.password_4.setFont(font)
        self.password_4.setObjectName("password_4")
        self.passwordEdit = QtWidgets.QLineEdit(registerForm)
        self.passwordEdit.setGeometry(QtCore.QRect(220, 210, 200, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordEdit.sizePolicy().hasHeightForWidth())
        self.passwordEdit.setSizePolicy(sizePolicy)
        self.passwordEdit.setMinimumSize(QtCore.QSize(200, 30))
        self.passwordEdit.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.passwordEdit.setFont(font)
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setClearButtonEnabled(True)
        self.passwordEdit.setObjectName("passwordEdit")
        self.usernameEdit = QtWidgets.QLineEdit(registerForm)
        self.usernameEdit.setGeometry(QtCore.QRect(220, 150, 200, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usernameEdit.sizePolicy().hasHeightForWidth())
        self.usernameEdit.setSizePolicy(sizePolicy)
        self.usernameEdit.setMinimumSize(QtCore.QSize(200, 30))
        self.usernameEdit.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setKerning(False)
        self.usernameEdit.setFont(font)
        self.usernameEdit.setText("")
        self.usernameEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.usernameEdit.setPlaceholderText("")
        self.usernameEdit.setClearButtonEnabled(True)
        self.usernameEdit.setObjectName("usernameEdit")
        self.confirmEdit = QtWidgets.QLineEdit(registerForm)
        self.confirmEdit.setGeometry(QtCore.QRect(220, 270, 200, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirmEdit.sizePolicy().hasHeightForWidth())
        self.confirmEdit.setSizePolicy(sizePolicy)
        self.confirmEdit.setMinimumSize(QtCore.QSize(200, 30))
        self.confirmEdit.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setKerning(False)
        self.confirmEdit.setFont(font)
        self.confirmEdit.setText("")
        self.confirmEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmEdit.setPlaceholderText("")
        self.confirmEdit.setClearButtonEnabled(True)
        self.confirmEdit.setObjectName("confirmEdit")
        self.label = QtWidgets.QLabel(registerForm)
        self.label.setGeometry(QtCore.QRect(-10, -60, 691, 541))
        self.label.setStyleSheet("image: url(:/register/login_650_400.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.backButton.raise_()
        self.registerButton.raise_()
        self.phoneNumberLabel.raise_()
        self.numberEdit.raise_()
        self.password_9.raise_()
        self.codeLabel.raise_()
        # self.codeEdit.raise_()
        # self.sendCodeButton.raise_()
        self.usernameLabel.raise_()
        self.passwordLabel.raise_()
        self.confirmLabel.raise_()
        self.tel_2.raise_()
        self.password_4.raise_()
        self.passwordEdit.raise_()
        self.password_3.raise_()
        self.usernameEdit.raise_()
        self.confirmEdit.raise_()

        self.retranslateUi(registerForm)
        self.backButton.clicked.connect(registerForm.backtoLogin)
        self.registerButton.clicked.connect(registerForm.registerSuccess)
        # self.sendCodeButton.clicked.connect(registerForm.sendCode)
        # self.codeEdit.textChanged['QString'].connect(registerForm.codeChanged)
        self.numberEdit.textChanged['QString'].connect(registerForm.phoneChanged)
        QtCore.QMetaObject.connectSlotsByName(registerForm)

    def retranslateUi(self, registerForm):
        _translate = QtCore.QCoreApplication.translate
        registerForm.setWindowTitle(_translate("registerForm", "注册"))
        self.backButton.setText(_translate("registerForm", "返回"))
        self.registerButton.setText(_translate("registerForm", "注册"))
        self.phoneNumberLabel.setText(_translate("registerForm", "手机号"))
        self.password_9.setText(_translate("registerForm", "请输入手机号"))
        # self.codeLabel.setText(_translate("registerForm", "验证码"))
        # self.sendCodeButton.setText(_translate("registerForm", "发送验证码"))
        self.usernameLabel.setText(_translate("registerForm", "用户名"))
        self.passwordLabel.setText(_translate("registerForm", "设置密码"))
        self.confirmLabel.setText(_translate("registerForm", "确认密码"))
        self.tel_2.setText(_translate("registerForm", "请输入用户名"))
        self.password_3.setText(_translate("registerForm", "6-10位大小写字母和数字"))
        self.password_4.setText(_translate("registerForm", "请确认密码"))
import back_rc
