# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'score.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_scoreForm(object):
    def setupUi(self, scoreForm):
        scoreForm.setObjectName("scoreForm")
        scoreForm.resize(650, 400)
        scoreForm.setMinimumSize(QtCore.QSize(650, 400))
        scoreForm.setMaximumSize(QtCore.QSize(650, 400))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(18)
        scoreForm.setFont(font)
        self.centralwidget = QtWidgets.QWidget(scoreForm)
        self.centralwidget.setObjectName("centralwidget")
        self.backtochoiceButton = QtWidgets.QPushButton(self.centralwidget)
        self.backtochoiceButton.setGeometry(QtCore.QRect(530, 330, 120, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.backtochoiceButton.setFont(font)
        self.backtochoiceButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backtochoiceButton.setMouseTracking(False)
        self.backtochoiceButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.backtochoiceButton.setStyleSheet("border-image: url(:/button/button.png);")
        self.backtochoiceButton.setIconSize(QtCore.QSize(20, 20))
        self.backtochoiceButton.setObjectName("backtochoiceButton")
        self.backtologinButton = QtWidgets.QPushButton(self.centralwidget)
        self.backtologinButton.setGeometry(QtCore.QRect(50, 30, 90, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.backtologinButton.setFont(font)
        self.backtologinButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backtologinButton.setStyleSheet("border-image: url(:/button/button.png);")
        self.backtologinButton.setObjectName("backtologinButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 50, 240, 80))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.scoreLabel = QtWidgets.QLabel(self.centralwidget)
        self.scoreLabel.setGeometry(QtCore.QRect(190, 130, 240, 80))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(50)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.scoreLabel.setFont(font)
        self.scoreLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.scoreLabel.setObjectName("scoreLabel")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(165, 230, 320, 80))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName("label2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 650, 400))
        self.label_2.setStyleSheet("image: url(:/register/login_650_400.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.changeSecretButton = QtWidgets.QPushButton(self.centralwidget)
        self.changeSecretButton.setGeometry(QtCore.QRect(500, 30, 90, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.changeSecretButton.setFont(font)
        self.changeSecretButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.changeSecretButton.setStyleSheet("border-image: url(:/button/button.png);")
        self.changeSecretButton.setObjectName("changeSecretButton")
        self.label_2.raise_()
        self.backtochoiceButton.raise_()
        self.backtologinButton.raise_()
        self.label.raise_()
        self.scoreLabel.raise_()
        self.label2.raise_()
        self.changeSecretButton.raise_()
        scoreForm.setCentralWidget(self.centralwidget)

        self.retranslateUi(scoreForm)
        self.backtologinButton.clicked.connect(scoreForm.backToLogin)
        self.backtochoiceButton.clicked.connect(scoreForm.backToChoice)
        self.changeSecretButton.clicked.connect(scoreForm.toChange)
        QtCore.QMetaObject.connectSlotsByName(scoreForm)

    def retranslateUi(self, scoreForm):
        _translate = QtCore.QCoreApplication.translate
        scoreForm.setWindowTitle(_translate("scoreForm", "题题会"))
        self.backtochoiceButton.setText(_translate("scoreForm", "再来一套🙃"))
        self.backtologinButton.setText(_translate("scoreForm", "退出登录"))
        self.label.setText(_translate("scoreForm", "您的得分为："))
        self.scoreLabel.setText(_translate("scoreForm", "score"))
        self.label2.setText(_translate("scoreForm", "人生在勤，不索何获！"))
        self.changeSecretButton.setText(_translate("scoreForm", "修改密码"))
import back_rc
