# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_questions.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setquestionForm(object):
    def setupUi(self, setquestionForm):
        setquestionForm.setObjectName("setquestionForm")
        setquestionForm.resize(650, 400)
        setquestionForm.setMinimumSize(QtCore.QSize(650, 400))
        setquestionForm.setMaximumSize(QtCore.QSize(650, 400))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(18)
        setquestionForm.setFont(font)
        setquestionForm.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(setquestionForm)
        self.centralwidget.setObjectName("centralwidget")
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(550, 20, 90, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.submitButton.setFont(font)
        self.submitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submitButton.setStyleSheet("border-image: url(:/button/button.png);")
        self.submitButton.setObjectName("submitButton")
        self.beforeQuesButton = QtWidgets.QPushButton(self.centralwidget)
        self.beforeQuesButton.setEnabled(True)
        self.beforeQuesButton.setGeometry(QtCore.QRect(20, 350, 90, 30))
        self.beforeQuesButton.setMaximumSize(QtCore.QSize(16000000, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.beforeQuesButton.setFont(font)
        self.beforeQuesButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.beforeQuesButton.setStyleSheet("border-image: url(:/button/button.png);")
        self.beforeQuesButton.setObjectName("beforeQuesButton")
        self.quitLoginButton = QtWidgets.QPushButton(self.centralwidget)
        self.quitLoginButton.setGeometry(QtCore.QRect(10, 20, 90, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.quitLoginButton.setFont(font)
        self.quitLoginButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.quitLoginButton.setStyleSheet("border-image: url(:/button/button.png);")
        self.quitLoginButton.setObjectName("quitLoginButton")
        self.setQuesButton = QtWidgets.QPushButton(self.centralwidget)
        self.setQuesButton.setGeometry(QtCore.QRect(130, 20, 90, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.setQuesButton.setFont(font)
        self.setQuesButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.setQuesButton.setStyleSheet("border-image: url(:/button/button.png);")
        self.setQuesButton.setObjectName("setQuesButton")
        self.nextQuesButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextQuesButton.setEnabled(True)
        self.nextQuesButton.setGeometry(QtCore.QRect(540, 350, 90, 30))
        self.nextQuesButton.setMaximumSize(QtCore.QSize(16000000, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.nextQuesButton.setFont(font)
        self.nextQuesButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nextQuesButton.setStyleSheet("border-image: url(:/button/button.png);")
        self.nextQuesButton.setObjectName("nextQuesButton")
        self.changeSecretButton = QtWidgets.QPushButton(self.centralwidget)
        self.changeSecretButton.setGeometry(QtCore.QRect(450, 20, 90, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.changeSecretButton.setFont(font)
        self.changeSecretButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.changeSecretButton.setStyleSheet("border-image: url(:/button/button.png);")
        self.changeSecretButton.setObjectName("changeSecretButton")
        self.quesNoLabel = QtWidgets.QLabel(self.centralwidget)
        self.quesNoLabel.setGeometry(QtCore.QRect(40, 63, 120, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.quesNoLabel.setFont(font)
        self.quesNoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.quesNoLabel.setObjectName("quesNoLabel")
        self.quesLabel = QtWidgets.QLabel(self.centralwidget)
        self.quesLabel.setGeometry(QtCore.QRect(60, 125, 650, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.quesLabel.setFont(font)
        self.quesLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.quesLabel.setObjectName("quesLabel")
        self.DLabel = QtWidgets.QLabel(self.centralwidget)
        self.DLabel.setGeometry(QtCore.QRect(227, 307, 30, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DLabel.setFont(font)
        self.DLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.DLabel.setObjectName("DLabel")
        self.ALabel = QtWidgets.QLabel(self.centralwidget)
        self.ALabel.setGeometry(QtCore.QRect(227, 187, 30, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ALabel.setFont(font)
        self.ALabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ALabel.setObjectName("ALabel")
        self.DRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.DRadio.setGeometry(QtCore.QRect(267, 307, 200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DRadio.setFont(font)
        self.DRadio.setText("")
        self.DRadio.setObjectName("DRadio")
        self.BRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.BRadio.setGeometry(QtCore.QRect(267, 227, 200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.BRadio.setFont(font)
        self.BRadio.setText("")
        self.BRadio.setObjectName("BRadio")
        self.ARadio = QtWidgets.QRadioButton(self.centralwidget)
        self.ARadio.setGeometry(QtCore.QRect(267, 187, 200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ARadio.setFont(font)
        self.ARadio.setText("")
        self.ARadio.setObjectName("ARadio")
        self.CLabel = QtWidgets.QLabel(self.centralwidget)
        self.CLabel.setGeometry(QtCore.QRect(227, 267, 30, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.CLabel.setFont(font)
        self.CLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.CLabel.setObjectName("CLabel")
        self.BLabel = QtWidgets.QLabel(self.centralwidget)
        self.BLabel.setGeometry(QtCore.QRect(227, 227, 30, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.BLabel.setFont(font)
        self.BLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.BLabel.setObjectName("BLabel")
        self.CRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.CRadio.setGeometry(QtCore.QRect(267, 267, 200, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.CRadio.setFont(font)
        self.CRadio.setText("")
        self.CRadio.setObjectName("CRadio")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 650, 400))
        self.label.setStyleSheet("image: url(:/main/main_650_400.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.submitButton.raise_()
        self.beforeQuesButton.raise_()
        self.quitLoginButton.raise_()
        self.setQuesButton.raise_()
        self.nextQuesButton.raise_()
        self.changeSecretButton.raise_()
        self.quesLabel.raise_()
        self.DLabel.raise_()
        self.ALabel.raise_()
        self.DRadio.raise_()
        self.BRadio.raise_()
        self.ARadio.raise_()
        self.CLabel.raise_()
        self.BLabel.raise_()
        self.CRadio.raise_()
        self.quesNoLabel.raise_()
        setquestionForm.setCentralWidget(self.centralwidget)

        self.retranslateUi(setquestionForm)
        self.quitLoginButton.clicked.connect(setquestionForm.quitToLogin)
        self.setQuesButton.clicked.connect(setquestionForm.quitToChoice)
        self.changeSecretButton.clicked.connect(setquestionForm.changeSecret)
        self.submitButton.clicked.connect(setquestionForm.submitNow)
        self.beforeQuesButton.clicked.connect(setquestionForm.beforQues)
        self.nextQuesButton.clicked.connect(setquestionForm.nextQues)
        self.ARadio.clicked.connect(setquestionForm.ifisChecked)
        self.BRadio.clicked.connect(setquestionForm.ifisChecked)
        self.CRadio.clicked.connect(setquestionForm.ifisChecked)
        self.DRadio.clicked.connect(setquestionForm.ifisChecked)
        QtCore.QMetaObject.connectSlotsByName(setquestionForm)

    def retranslateUi(self, setquestionForm):
        _translate = QtCore.QCoreApplication.translate
        setquestionForm.setWindowTitle(_translate("setquestionForm", "题题会"))
        self.submitButton.setText(_translate("setquestionForm", "提交"))
        self.beforeQuesButton.setText(_translate("setquestionForm", "☚上一题"))
        self.quitLoginButton.setText(_translate("setquestionForm", "退出登录"))
        self.setQuesButton.setText(_translate("setquestionForm", "重新出题"))
        self.nextQuesButton.setText(_translate("setquestionForm", "下一题☛"))
        self.changeSecretButton.setText(_translate("setquestionForm", "修改密码"))
        self.quesNoLabel.setText(_translate("setquestionForm", "第 X 题"))
        self.quesLabel.setText(_translate("setquestionForm", "题目1234"))
        self.DLabel.setText(_translate("setquestionForm", "D"))
        self.ALabel.setText(_translate("setquestionForm", "A "))
        self.CLabel.setText(_translate("setquestionForm", "C"))
        self.BLabel.setText(_translate("setquestionForm", "B "))
import back_rc
